services:
  workouse_link_preview_generator.twig_extension.link_preview_extension:
    class: Workouse\LinkPreviewGeneratorBundle\Twig\LinkPreviewExtension
    public: true
    tags:
      - { name: twig.extension }
